### PR TITLE
Fix `alex` version

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Trying to work out what's causing the CI to fall over in e.g. https://github.com/vehicle-lang/vehicle/actions/runs/4498380696/jobs/7914938112

### CODE REVIEW

**Comment by wenkokke** [comment]
We may need to report this upstream?

**Comment by MatthewDaggitt** [comment]
To the `setup-haskell` repo or to `alex` directly?

**Comment by MatthewDaggitt** [comment]
I'll try merging this in now and seeing if it'll fix it.

**Comment by wenkokke** [comment]
To haskell/cabal.

This is the error we’re running into:
https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/Cabal/src/Distribution/Simple/Program/Db.hs#L489-L492

Which means that the function finding the Alex version in this definition is failing:
https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/Cabal/src/Distribution/Simple/Program/Builtin.hs#L239-L247

**Comment by MatthewDaggitt** [comment]
Drat the error has reoccured.

Opened https://github.com/haskell/cabal/issues/8876

**Pull request merged**
