### PR TITLE
Fix performance problems by temporarily changing cabal library used for executable component

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Fixes the latest performance problems reported in https://github.com/vehicle-lang/vehicle/issues/331. Reduces benchmark execution time on my machine from `27.984 s ±  2.241 s` to `5.730 s ±  0.218 s` on my machine. And from 22 s to 2 s when running the test suite normally.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
@wenkokke the `GHC 9.2.4 -fghc-debug` and `GHC 9.2.4 -fghc-debug -fnothunks` CI tests are taking over an hour, is that expected?

**Comment by MatthewDaggitt** [comment]
I've disabled the `-fghc-debug` builds as they seem to be never terminating. Unsure whether that's because of the change I've made to the `.cabal` file or not.

**Comment by wenkokke** [comment]
> I've disabled the `-fghc-debug` builds as they seem to be never terminating. Unsure whether that's because of the change I've made to the `.cabal` file or not.

They're not running because ghc-debug requires the `-threaded` RTS option, and removing it basically deadlocks the process.

**Comment by wenkokke** [comment]
This actually introduces a 100% performance penalty for me, going from 10s to 20s.

**Pull request merged**
