### PR TITLE
Fix: only pass `-threaded` and `-N` if `--ghc-debug` is set

### PR DESCRIPTION
**Pull request by wenkokke**
@MatthewDaggitt please benchmark these changes, as the 2nd performance regression isn't detectable on my system.

### CODE REVIEW

**Comment by wenkokke** [comment]
This should fix performance _for you_ but actually still introduces a 100% slowdown for me, going from 10s to 20s.

**Comment by MatthewDaggitt** [comment]
Hmmm so
- current dev: benchmark `5.911 s ±  0.196 s`, repeated manual individual runs `1.96s`
- this branch: benchmark `8.871 s ±  0.027 s`, repeated manual individual runs `9.73s`

So there's still some slow-down....

**Comment by wenkokke** [comment]
How, though? There literally shouldn't be any difference if you're not building with ghc-debug?

Could it be noise? Are you running these benchmarks using scripts/benchmark on a computer with no other programs running?

**Comment by MatthewDaggitt** [comment]
> How, though? There literally shouldn't be any difference if you're not building without ghc-debug?

Did you mean this double-negative?

> Could it be noise? Are you running these benchmarks using scripts/benchmark on a computer with no other programs running?

Yup. No other programs running. The first numbers are obtained by running `./scripts/benchmark`.

Are you free to call at some point tomorrow and we can try and work it out?

**Comment by wenkokke** [comment]
> > How, though? There literally shouldn't be any difference if you're not building without ghc-debug?
> 
> Did you mean this double-negative?

I did not.

**Comment by wenkokke** [comment]
Maybe it’s time for the Haskell mailing list?

**Pull request merged**
