### PR TITLE
added installation instructions

### PR DESCRIPTION
**Pull request by Yiergot**
initial guide to get started with vehicle, won't be final README

### CODE REVIEW

**Comment by wenkokke** [comment]
Not sure this is exactly the right way, and I’d like to stay away from `—allow-newer` as it is *bonkers*.

**Comment by wenkokke** [comment]
I think the right way to go is to call `stack install bnfc` from the vehicle directory.
We could do from the Makefile if BNFC isn’t found, and let `BNFC=stack exec bnfc`?

**Comment by Yiergot** [comment]
just tested on the vm, 'stack update' and then 'stack install BNFC' (case sensitive) works as well. Can remove the thing about binary download.

**Comment by wenkokke** [comment]
@MatthewDaggitt and I are working on a more comprehensive fix

**Pull request closed without merging**
