### PR TITLE
Try to fix the CI

### PR DESCRIPTION
**Pull request by MatthewDaggitt**
Made this a PR to avoid making endless minor commits.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Okay, well we're installing `bnfc`/`alex`/`happy` but the `findExecutable` and `cmd` commands can't find them at all... Giving up on this for today.

**Comment by wenkokke** [comment]
Once we have this working shell we add operating systems to the testing matrix as well? Makes sure we don't lose that windows compatibility?

**Comment by MatthewDaggitt** [comment]
Absolutely. Just need to get it working first :smile:

**Comment by wenkokke** [comment]
Let me know if you would like some help with this. I have spent more hours than I am willing to admit wrestling with a CI.

**Pull request merged**
