### PR TITLE
Refactor integration tests

### PR DESCRIPTION
**Pull request by wenkokke**

### CODE REVIEW

**Comment by wenkokke** [comment]
Future work:
- Change SomeOption to have one LocalOption constructor and one AdjustOption constructor, which call the respective functions.
- Change --external-only to use safeReadBool and flagCLParser
- Change --external, --ignore-files, and --ignore-lines to take comma separated lists

**Comment by MatthewDaggitt** [comment]
I dislike this change from `compiler-tests` to `golden-tests`. The integration tests are also golden tests...

**Comment by MatthewDaggitt** [comment]
`compiler-tests` was much more descriptive.

**Comment by MatthewDaggitt** [comment]
Oh I see, the integration tests have been folded into the golden tests.

**Pull request merged**
